<?php

/*
 * Создает единый файл bx_1c_sync.php из исходников в /src
 */

$srcDir = __DIR__ . '/src';
$outputFile = __DIR__ . '/bx_1c_sync.php';

$indexContent = file_get_contents($srcDir . '/index.php');

preg_match_all("#require\('\./(.+?)'\);#", $indexContent, $matches);

$indexReplace = [];

foreach ($matches[0] as $key => $match) {
	$file = $matches[1][$key];
	
	$ext = pathinfo($file, PATHINFO_EXTENSION);
	$filename = "{$srcDir}/{$file}";
	
	if (! file_exists($filename)) {
		continue;
	}
	
	$content = file_get_contents($filename);
	
	$content = " /* {$file} => */ ?>{$content}";
	if ($ext !== 'php')
	{
		$content = "{$content}<?php";
	}
	
	$indexReplace[$match] = $content;
}

$indexContent = str_replace(array_keys($indexReplace), array_values($indexReplace), $indexContent);

preg_match_all('#\<link rel\="stylesheet" href\="\./(.+?)"\>#', $indexContent, $styles);
preg_match_all('#\<script src\="\./(.+?)"\>\</script\>#', $indexContent, $scripts);

$matches = [
	array_merge($styles[0], $scripts[0]),
	array_merge($styles[1], $scripts[1]),
];
$indexReplace = [];

foreach ($matches[0] as $key => $match) {
	$file = $matches[1][$key];
	
	$ext = pathinfo($file, PATHINFO_EXTENSION);
	$filename = "{$srcDir}/{$file}";
	
	if (! file_exists($filename)) {
		continue;
	}
	
	$content = file_get_contents($filename);
	
	if ($ext === 'css')
	{
		$content = "<style>{$content}</style>";
	}
	if ($ext === 'js')
	{
		$content = "<script>{$content}</script>";
	}
	
	$indexReplace[$match] = $content;
}
$indexContent = str_replace(array_keys($indexReplace), array_values($indexReplace), $indexContent);

$indexContent = "<?php /*\r\n\r\nAUTOGENERATED.\r\nAbout script: https://github.com/MashinaMashina/bx_1c_sync \r\n\r\n*/ ?>{$indexContent}";
file_put_contents($outputFile, $indexContent);